routes/web.php
<?php
 
/* 
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
| 
*/

// Route::get('/', function() {
// 	return view('home.main');
// });
//  
// 
// v2.0 awal
// 
// Lini 1
//
Route::get('/lini1identifikasi/showST/{id}', 'lini1\Lini1IdentifikasiCtrl@showST2');
Route::get('/lini1analisis/kemungkinan', 'lini1\Lini1AnalisisCtrl@kemungkinan');
Route::get('/lini1analisis/dampak', 'lini1\Lini1AnalisisCtrl@dampak');
Route::get('/lini1analisis/showECedit/{id}', 'lini1\Lini1AnalisisCtrl@showECedit');
Route::get('/lini1analisis/showEC/{id}', 'lini1\Lini1AnalisisCtrl@showEC');
Route::get('/lini1realisasi/pilihPeriodeRTP/{id}', 'lini1\Lini1RealisasiCtrl@pilihPeriodeRTP');
Route::get('/lini1identifikasi/risikotreated', 'lini1\Lini1IdentifikasiCtrl@risikoTreated');
Route::get('/lini1identifikasi/risikoresidual', 'lini1\Lini1IdentifikasiCtrl@risikoResidual');
Route::get('/lini1identifikasi/risikoinherent', 'lini1\Lini1IdentifikasiCtrl@risikoInherent');
Route::get('/lini1identifikasi/api', 'lini1\Lini1IdentifikasiCtrl@tesAPI');

Route::group(['middleware' => ['web', 'auth', 'roles']],function() {
Route::group(['roles' => '3' or '4' or '5' or '6' or '7' or '9' or '10'],function() { 
Route::namespace('lini1')->group(function () {

Route::get('dashboardunit', ['uses' => 'Lini1DashboardCtrl@index', 'as' => 'dashboardunit']);

// Parameter
// 
// BPKP
Route::get('lini1databpkp', ['uses' => 'Lini1DataBPKPCtrl@index', 'as' => 'lini1databpkp']);
Route::resource('lini1databpkp', 'Lini1DataBPKPCtrl');
Route::get('createusbpkp', ['uses' => 'Lini1UsulanCtrl@createusbpkp', 'as' => 'createusbpkp']);
// Unit Kerja Mandiri
Route::get('lini1data', ['uses' => 'Lini1DataCtrl@index', 'as' => 'lini1data']);
Route::resource('lini1data', 'Lini1DataCtrl');
Route::get('lini1panduan', ['uses' => 'Lini1DokumenCtrl@panduan', 'as' => 'lini1panduan']);
Route::get('lini1kamus', ['uses' => 'Lini1KamusCtrl@index', 'as' => 'lini1kamus']);
Route::get('cetakkamus', 'Lini1KamusCtrl@cetak');
Route::get('cetak01', 'Lini1KamusCtrl@cetak01');
Route::get('cetak02', 'Lini1KamusCtrl@cetak02');
Route::get('cetak03', 'Lini1KamusCtrl@cetak03');
Route::get('cetak04', 'Lini1KamusCtrl@cetak04');
Route::get('cetak05', 'Lini1KamusCtrl@cetak05');
Route::get('cetak06', 'Lini1KamusCtrl@cetak06');
Route::get('createusunit', ['uses' => 'Lini1UsulanCtrl@createusunit', 'as' => 'createusunit']);
Route::get('lini1usul', ['uses' => 'Lini1UsulanCtrl@index', 'as' => 'lini1usul']);
Route::resource('lini1usulan', 'Lini1UsulanCtrl');

// Penetapan Konteks
// 
// BPKP
Route::get('createtkbpkp', ['uses' => 'Lini1TetapKonteksBPKPCtrl@create', 'as' => 'createtkbpkp']);
Route::get('lini1tetapkonteksbpkp', ['uses' => 'Lini1TetapKonteksBPKPCtrl@index', 'as' => 'lini1tetapkonteksbpkp']);
Route::resource('lini1tetapkonteksbpkp', 'Lini1TetapKonteksBPKPCtrl');
// Unit Kerja Mandiri
Route::get('exceltkunit', 'Lini1TetapKonteksCtrl@excel');
Route::get('createtkunit', ['uses' => 'Lini1TetapKonteksCtrl@create', 'as' => 'createtkunit']);
Route::get('lini1tetapkonteks', ['uses' => 'Lini1TetapKonteksCtrl@index', 'as' => 'lini1tetapkonteks']);
Route::resource('lini1tetapkonteks', 'Lini1TetapKonteksCtrl');
Route::get('createstakeunit', ['uses' => 'Lini1StakeholderCtrl@create', 'as' => 'createstakeunit']);
Route::get('lini1stakeholder', ['uses' => 'Lini1StakeholderCtrl@index', 'as' => 'lini1stakeholder']);
Route::resource('lini1stakeholder', 'Lini1StakeholderCtrl');


// Identifikasi Risiko
// 
// BPKP
Route::get('heatmapbpkp', ['uses' => 'Lini1IdentifikasiBPKPCtrl@getHeatmapBPKP', 'as' => 'heatmapbpkp']);
Route::get('heatmapbpkpi', ['uses' => 'Lini1IdentifikasiBPKPCtrl@getHeatmapBPKPi', 'as' => 'heatmapbpkpi']);
Route::get('heatmapbpkpr', ['uses' => 'Lini1IdentifikasiBPKPCtrl@getHeatmapBPKPr', 'as' => 'heatmapbpkpr']);
Route::get('dashboardregisterbpkp', 'Lini1IdentifikasiBPKPCtrl@getDashRegisterBPKP');
Route::get('dashboardregisterbpkp/{id}', 'Lini1IdentifikasiBPKPCtrl@getFilterRegisterBPKP');
Route::get('excelan', 'Lini1IdentifikasiBPKPCtrl@excelan');
Route::get('excelrtp', 'Lini1IdentifikasiBPKPCtrl@excelrtp');
Route::get('excelmon', 'Lini1IdentifikasiBPKPCtrl@excelmon');
Route::get('excelidbpkp/{id}', 'Lini1IdentifikasiBPKPCtrl@excel');
Route::get('excelidall', 'Lini1IdentifikasiBPKPCtrl@excelall');
Route::get('excelecbpkp/{id}', 'Lini1IdentifikasiBPKPCtrl@excelec');
Route::get('excelecall', 'Lini1IdentifikasiBPKPCtrl@excelecall');
Route::get('cetakidbpkp', 'Lini1IdentifikasiBPKPCtrl@cetak');
Route::get('createidbpkp', ['uses' => 'Lini1IdentifikasiBPKPCtrl@create', 'as' => 'createidbpkp']);
Route::get('lini1identifikasibpkp', ['uses' => 'Lini1IdentifikasiBPKPCtrl@index', 'as' => 'lini1identifikasibpkp']);
Route::resource('lini1identifikasibpkp', 'Lini1IdentifikasiBPKPCtrl');
// Unit Kerja Mandiri
Route::get('heatmapunit', ['uses' => 'Lini1IdentifikasiCtrl@getHeatmapUnit', 'as' => 'heatmapunit']);
Route::get('heatmapuniti', ['uses' => 'Lini1IdentifikasiCtrl@getHeatmapUniti', 'as' => 'heatmapuniti']);
Route::get('heatmapunitr', ['uses' => 'Lini1IdentifikasiCtrl@getHeatmapUnitr', 'as' => 'heatmapunitr']);
Route::get('dashboardregisterunit', 'Lini1IdentifikasiCtrl@getDashRegisterUnit');
Route::get('dashboardregisterunit/{id}', 'Lini1IdentifikasiCtrl@getFilterRegisterUnit');
Route::get('excelidunit', 'Lini1IdentifikasiCtrl@excel');
Route::get('excelecunit', 'Lini1IdentifikasiCtrl@excelec');
Route::get('cetakidunit', 'Lini1IdentifikasiCtrl@cetak');
Route::get('createidunit', ['uses' => 'Lini1IdentifikasiCtrl@create', 'as' => 'createidunit']);
Route::get('lini1identifikasi', ['uses' => 'Lini1IdentifikasiCtrl@index', 'as' => 'lini1identifikasi']);
Route::resource('lini1identifikasi', 'Lini1IdentifikasiCtrl');

// Analisis Risiko
// 
// BPKP
Route::get('skoranbpkp', 'Lini1AnalisisBPKPCtrl@getSkorAnBPKP');
Route::get('cetakanbpkp', 'Lini1AnalisisBPKPCtrl@cetak');
Route::get('createanbpkp', ['uses' => 'Lini1AnalisisBPKPCtrl@create', 'as' => 'createanbpkp']);
Route::get('lini1analisisbpkp', ['uses' => 'Lini1AnalisisBPKPCtrl@index', 'as' => 'lini1analisisbpkp']);
Route::resource('lini1analisisbpkp', 'Lini1AnalisisBPKPCtrl');
Route::get('lini1pengendalianbpkp/{id}/tambah', ['as' => 'lini1pengendalianbpkp.tambah', 'uses' => 'Lini1PengendalianBPKPCtrl@tambah']);
Route::get('lini1pengendalianbpkp', ['uses' => 'Lini1PengendalianBPKPCtrl@index', 'as' => 'lini1pengendalianbpkp']);
Route::resource('lini1pengendalianbpkp', 'Lini1PengendalianBPKPCtrl');
Route::get('lini1residualbpkp', ['uses' => 'Lini1ResidualBPKPCtrl@index', 'as' => 'lini1residualbpkp']);
Route::resource('lini1residualbpkp', 'Lini1ResidualBPKPCtrl');
// Unit Kerja Mandiri
Route::get('skoranunit', 'Lini1AnalisisCtrl@getSkorAnUnit');
Route::get('cetakanunit', 'Lini1AnalisisCtrl@cetak');
Route::get('cetaktrenunit', 'Lini1AnalisisCtrl@cetaktren');
Route::get('createanunit', ['uses' => 'Lini1AnalisisCtrl@create', 'as' => 'createanunit']);
Route::get('lini1analisis', ['uses' => 'Lini1AnalisisCtrl@index', 'as' => 'lini1analisis']);
Route::resource('lini1analisis', 'Lini1AnalisisCtrl');
Route::get('lini1pengendalian/{id}/tambah', ['as' => 'lini1pengendalian.tambah', 'uses' => 'Lini1PengendalianCtrl@tambah']);
Route::get('lini1pengendalian', ['uses' => 'Lini1PengendalianCtrl@index', 'as' => 'lini1pengendalian']);
Route::resource('lini1pengendalian', 'Lini1PengendalianCtrl');
Route::get('lini1residual', ['uses' => 'Lini1ResidualCtrl@index', 'as' => 'lini1residual']);
Route::resource('lini1residual', 'Lini1ResidualCtrl');

// Evaluasi Risiko
// 
// BPKP
Route::get('penyebabbpkp', 'Lini1EvaluasiBPKPCtrl@getPenyebabBPKP');
Route::get('penyebablistbpkp', 'Lini1EvaluasiBPKPCtrl@getPenyebabListBPKP');
Route::get('penyebablistbpkp/{id}', 'Lini1EvaluasiBPKPCtrl@getFilterPenyebabListBPKP');
Route::get('cetakevbpkp', 'Lini1EvaluasiBPKPCtrl@cetakRisiko');
Route::get('cetakrcabpkp', 'Lini1EvaluasiBPKPCtrl@cetakRCA');
Route::get('createevbpkp', ['uses' => 'Lini1EvaluasiBPKPCtrl@create', 'as' => 'createevbpkp']);
Route::get('lini1evaluasibpkp', ['uses' => 'Lini1EvaluasiBPKPCtrl@index', 'as' => 'lini1evaluasibpkp']);
Route::resource('lini1evaluasibpkp', 'Lini1EvaluasiBPKPCtrl');
// Unit Kerja Mandiri
Route::get('penyebabunit', 'Lini1EvaluasiCtrl@getPenyebabUnit');
Route::get('penyebablistunit', 'Lini1EvaluasiCtrl@getPenyebabListUnit');
Route::get('penyebablistunit/{id}', 'Lini1EvaluasiCtrl@getFilterPenyebabListUnit');
Route::get('cetakevunit', 'Lini1EvaluasiCtrl@cetakRisiko');
Route::get('cetakrcaunit', 'Lini1EvaluasiCtrl@cetakRCA');
Route::get('createevunit', ['uses' => 'Lini1EvaluasiCtrl@create', 'as' => 'createevunit']);
Route::get('lini1evaluasi', ['uses' => 'Lini1EvaluasiCtrl@index', 'as' => 'lini1evaluasi']);
Route::resource('lini1evaluasi', 'Lini1EvaluasiCtrl');

// Respons Risiko (Rencana)
// 
// BPKP
Route::get('rtpbpkp', 'Lini1ResponsBPKPCtrl@getRTPBPKP');
Route::get('rtplistbpkp', 'Lini1ResponsBPKPCtrl@getRTPListBPKP');
Route::get('rtplistcurbpkp', 'Lini1ResponsBPKPCtrl@getRTPListCurBPKP');
Route::get('cetakresbpkp', 'Lini1ResponsBPKPCtrl@cetak');
Route::get('createrespbpkp', ['uses' => 'Lini1ResponsBPKPCtrl@create', 'as' => 'createrespbpkp']);
Route::get('lini1responsbpkp', ['uses' => 'Lini1ResponsBPKPCtrl@index', 'as' => 'lini1responsbpkp']);
Route::resource('lini1responsbpkp', 'Lini1ResponsBPKPCtrl');
Route::get('lini1treatedbpkp', ['uses' => 'Lini1TreatedBPKPCtrl@index', 'as' => 'lini1treatedbpkp']);
Route::resource('lini1treatedbpkp', 'Lini1TreatedBPKPCtrl');
// Unit Kerja Mandiri
Route::get('rtpunit', 'Lini1ResponsCtrl@getRTPUnit');
Route::get('rtplistunit', 'Lini1ResponsCtrl@getRTPListUnit');

resources/views/lini1usulan/createus.blade.php
@extends('layout.app')
 
@section('isi')
<div class="slim-pageheader">
  <ol class="breadcrumb slim-breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('heatmapunit')}}"><i class="fa fa-home"></i> Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('lini1usul')}}">Usulan Risiko Baru</a></li>
    <li class="breadcrumb-item active" aria-current="page">Tambah Usulan</li>
  </ol>
  <h6 class="slim-pagetitle">Usulan Risiko Baru</h6>
</div><!-- slim-pageheader -->
<div class="card card-table">
  <div class="card-header">
    <h6 class="slim-card-title">Tambah Usulan</h6>
  </div>


  @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif


  @if (Auth::user()->role_id == '5'|Auth::user()->role_id == '7'|Auth::user()->role_id == '10')
  <form class="form-horizontal mt-2" action="{{route('lini1usulan.store')}}" method="post">
    {{ csrf_field() }}
    <div class="box-body">

      <div class="form-group" id="data-umum">
        <label for="s_kd_instansiunitorg" class="col-sm-2 control-label">Nama Unit</label>
        <div class="col-sm-12">
          <select name="s_kd_instansiunitorg" class="form-control" id="s_kd_instansiunitorg" autofocus>
            @foreach($s_kd_instansiunitorg as $key)
              <option value="{{$key->s_kd_instansiunitorg}}" {{old('s_kd_instansiunitorg') == $key ? 'selected' : ''}}>{{$key->s_kd_instansiunitorg}}</option>
            @endforeach
          </select>
        </div>
      </div>

      <div class="form-group">
        <label for="nama_bagan_risiko" class="col-sm-2 control-label">Nama Risiko</label>
          <div class="col-sm-12">
            <textarea class="form-control" name="nama_bagan_risiko">{{old('nama_bagan_risiko')}}</textarea>
          </div>
      </div>

      <div class="form-group">
        <label for="id_kategori_risiko" class="col-sm-2 control-label">Kategori Risiko</label>
        <div class="col-sm-12">
          <select name="id_kategori_risiko" class="form-control" id="id_kategori_risiko" autofocus>
            @foreach($id_kategori_risiko as $key => $value)
              <option value="{{$key}}" {{old('id_kategori_risiko') == $key ? 'selected' : ''}}>{{$value}}</option>
            @endforeach
          </select>
        </div>
      </div>

      <div class="form-group">
        <label for="id_tujuan_spip" class="col-sm-12 control-label">Metode Pencapaian Tujuan SPIP</label>
        <div class="col-sm-12">
          <select name="id_tujuan_spip" class="form-control" id="id_tujuan_spip" autofocus>
            @foreach($id_tujuan_spip as $key => $value)
              <option value="{{$key}}" {{old('id_tujuan_spip') == $key ? 'selected' : ''}}>{{$value}}</option>
            @endforeach
          </select>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-12">
          <button type="submit" class="btn btn-primary"> Simpan</button>
          <a href="{{route('lini1usulan.index')}}" type="submit" class="btn btn-danger"><i class="icon ion-android-cancel"></i> Batal</a>
        </div>
      </div>
      
    </div>
      <!-- /.box-body -->
  </form>
  @endif
</div>

@stop

@push('js')
<script type="text/javascript">
  $(document).ready(function() {
    $("#data-umum").hide();
    $("#s_kd_instansiunitorg").select2();
    $("#id_kategori_risiko").select2();
    $("#id_tujuan_spip").select2();
});
</script>
@endpush

resources/views/lini1usulan/index.blade.php
@extends('layout.app')
 
@section('isi')
<div class="slim-pageheader">
  <ol class="breadcrumb slim-breadcrumb">
    @if (Auth::user()->role_id == '3')
    <li class="breadcrumb-item"><a href="{{route('heatmapbpkp')}}"><i class="fa fa-home"></i> Home</a></li>
    @else
    <li class="breadcrumb-item"><a href="{{route('heatmapunit')}}"><i class="fa fa-home"></i> Home</a></li>
    @endif
    <li class="breadcrumb-item active" aria-current="page">Usulan Risiko Baru</li>
  </ol>
  <h6 class="slim-pagetitle">Usulan Risiko Baru</h6>
</div><!-- slim-pageheader -->
<div class="card card-table">
  @if (Auth::user()->role_id == '3')
  <div class="card-header">
  <a href="{{route('createusbpkp')}}" class="btn btn-primary"><i class="icon ion-plus-round"></i> Tambah Usulan</a>
  </div>
  @elseif (Auth::user()->role_id == '5'|Auth::user()->role_id == '7'|Auth::user()->role_id == '10')
  <div class="card-header">
  <a href="{{route('createusunit')}}" class="btn btn-primary"><i class="icon ion-plus-round"></i> Tambah Usulan</a>
  </div>
  @endif
  <!-- /.box-header -->
  <div class="pd-20">
    <div class="table-responsive-lg">
    <div class="table-wrapper">
    {{ csrf_field() }}

    <table id="tbl-identifikasi" class="table display">
      <thead align="center">
        <tr>
          <th width="3%">No.</th>
          <th style="text-align: center;">Nama Risiko</th>
          <th width="15%" style="text-align: center;">Kategori Risiko</th>
          <th width="15%" style="text-align: center;">Metode Pencapaian Tujuan SPIP</th>
          <th width="15%" style="text-align: center;">Status Usulan</th>
        </tr>
      </thead>
      <tbody>
      <?php $no=1; ?>
      @foreach($kamus as $item)
        <tr class="item{{$item->id}}">
          <td>{{$no++}}</td>
          <td>{{$item->nama_bagan_risiko}}</td>
          <td>{{$item->nama_kategori_risiko}}</td>
          <td>{{$item->nama_tujuan_spip}}</td>
          <td style="text-align: center;">
            @if($item->status_usulan == 1)
            <a href="{{route('lini1usulan.show', $item->id)}}" class="badge badge-primary"> Usulan Terkirim</a>
            @elseif($item->status_usulan == 2)
            <a href="{{route('lini1usulan.show', $item->id)}}" class="badge badge-danger"> Usulan Ditolak</a>
            @elseif($item->status_usulan == 3)
            <a href="{{route('lini1usulan.show', $item->id)}}" class="badge badge-warning"> Usulan Disetujui dengan Perbaikan</a>
            @elseif($item->status_usulan == 4)
            <a href="{{route('lini1usulan.show', $item->id)}}" class="badge badge-success"> Usulan Disetujui</a>
            @else
            Tidak ada data
            @endif
          </td>
        </tr>
      @endforeach
      </tbody>
    </table>
  </div>
  </div>
  </div>
</div>
@endsection

@push('js')
  <script>
  $(function(){
    'use strict';
    $('#tbl-identifikasi').DataTable({
      
      language: {
        searchPlaceholder: 'Search...',
        sSearch: '',
        lengthMenu: '_MENU_ items/page',
      }
    });

    // Select2
    $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });
  });

  </script>
@endpush

resources/views/lini1usulan/show.blade.php
@extends('layout.app')
 
@section('isi')
<div class="slim-pageheader">
  <ol class="breadcrumb slim-breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('heatmapunit')}}"><i class="fa fa-home"></i> Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('lini1usul')}}">Usulan Risiko Baru</a></li>
    <li class="breadcrumb-item active" aria-current="page">Detail Usulan Risiko Baru</li>
  </ol>
  <h6 class="slim-pagetitle">Detail Usulan Risiko Baru</h6>
</div><!-- slim-pageheader -->
<div class="card card-table"> 
  <div class="card-body">
    <div class="row">
      <div class="col-sm-12">  
        
        <span>Nama Risiko : </span>
        <p style="color: black;">{{$usulan->nama_bagan_risiko}}</p>     
      
        <span>Kategori Risiko : </span>
        <p style="color: black;">{{$usulan->nama_kategori_risiko}}</p>
  
        <span>Metode Pencapaian Tujuan SPIP : </span>
        <p style="color: black;">{{$usulan->nama_tujuan_spip}}</p>
      
        <span>Status Usulan : </span>
        <p>
          @if($usulan->status_usulan == 1)
            <span class="badge badge-primary">Usulan Terkirim</span>
          @elseif($usulan->status_usulan == 2)
            <span class="badge badge-danger">Usulan Ditolak</span>
          @elseif($usulan->status_usulan == 3)
            <span class="badge badge-warning">Usulan Disetujui dengan Perbaikan</span>
          @elseif($usulan->status_usulan == 4)
            <span class="badge badge-success">Usulan Disetujui</span>
          @else
            Tidak ada data
          @endif
        </p>

        @if(is_null($usulan->tanggapan))
        @else
        <span>Keterangan Usulan : </span>
          <p style="color: black;">{{$usulan->tanggapan}}</p>
        @endif

      </div>
    </div>
  </div>
</div>

@stop